version: '3.9'
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    hostname: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    ports:
      - "1000:9000"
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    volumes:
      - mongoData:/data/db
      - mongoConfig:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
  web:
    image: web
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: web
    hostname: web
    env_file:
      -.env
    command: wait-for-it --strict --timeout=120 web:80 -- sh -c "
      ./manage.py dbenv i
      uvicorn app.app:app --host 0.0.0.0 --port 80
      "
    restart: always
    volumes:
      - web:/code
    ports:
      - "80:80"
volumes:
  portainer:
    name: portainer
  mongoData:
    name: mongoData
  mongoConfig:
    name: mongoConfig
  web:
    name: web
