# 初始化激活-程序变量请问请勿设置
[init]
switch = false
# 共用
[shared]
tz_info = 'Asia/Shanghai'
# 数据库
[mongodb]
host = '127.0.0.1'
username ='spb0122003'
password ='dcaGRzkJpuKsHgMs8hoS'
# 令牌配置
[jwt]
secret_key = '09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7'
algorithm = 'HS256'
minutes=30